# Paths for NEORV32
NEORV32_HOME = ../../dependencies/neorv32
OUPWB_HOME = ../../dependencies/oup-wishbone
OUPWB_INC = -I $(OUPWB_HOME)/sw

# Override default includes
APP_INC = -I . $(OUPWB_INC) 

# Use NEORV32's excellent makefile
include $(NEORV32_HOME)/sw/common/common.mk